### ISSUE TITLE
[어드벤쳐 보스] Challenge 실패후 재도전시 아우라 교체하면 99 에러 발생

### ISSUE THREAD

**Issue by jaeho0103** [planetarium/NineChronicles#5265]
### APV version info

v200200

### Client version info

v200.0.1

### Device

Windows

### account address info

0x8129A10a23d468377c2e0CE553B4914C161c158B

### avatar address info

0x8129A10a23d468377c2e0CE553B4914C161c158B

### What happened?

Challenge 도전후 특정층에서 실패 
재도전시 Aura를 갈아입히면 99번 에러로 전투 결과 렌더 못함(AP포션 소모도 없는듯)

(제보에 의하면 1-5층은 괜찮다고 함, 6-10층에서 이슈 발생, 11층 이상은 못가서 확인불가)

### How to reproduce the issue

1. Click Button
2. Crash

**Comment by jaeho0103** [comment]
https://planetariumhq.slack.com/archives/C011716SDTM/p1719910148648839
최초 제보 받은 슬랙쓰레드이며, 동일한 부분 저도 발생 체크했습니다.

**Comment by U-lis** [comment]
error log
```action #0 exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at Nekoyume.Model.Buff.IceShield.FrostBite(StatBuffSheet statBuffSheet, BuffLinkSheet buffLinkSheet) in /home/ulismoon/Documents/planetarium/NineChronicles.Headless/Lib9c/Lib9c/Model/Buff/IceShield.cs:line 29
   at Nekoyume.Model.CharacterBase.OnPostSkill(Skill usedSkill) in /home/ulismoon/Documents/planetarium/NineChronicles.Headless/Lib9c/Lib9c/Model/Character/CharacterBase.cs:line 703
   at Nekoyume.Model.CharacterBase.Act() in /home/ulismoon/Documents/planetarium/NineChronicles.Headless/Lib9c/Lib9c/Model/Character/CharacterBase.cs:line 605
   at BTAI.Action.Tick() in /home/ulismoon/Documents/planetarium/NineChronicles.Headless/Lib9c/BTAI/BT.cs:line 160
   at BTAI.Root.Tick() in /home/ulismoon/Documents/planetarium/NineChronicles.Headless/Lib9c/BTAI/BT.cs:line 309
   at Nekoyume.Model.CharacterBase.Tick() in /home/ulismoon/Documents/planetarium/NineChronicles.Headless/Lib9c/Lib9c/Model/Character/CharacterBase.cs:line 215
   at Nekoyume.Battle.AdventureBoss.AdventureBossSimulator.Simulate() in /home/ulismoon/Documents/planetarium/NineChronicles.Headless/Lib9c/Lib9c/Battle/AdventureBoss/AdventureBossSimulator.cs:line 192
   at Nekoyume.Action.AdventureBoss.ExploreAdventureBoss.Execute(IActionContext context) in /home/ulismoon/Documents/planetarium/NineChronicles.Headless/Lib9c/Lib9c/Action/AdventureBoss/ExploreAdventureBoss.cs:line 296
   at NineChronicles.Headless.Executable.Commands.ReplayCommand.EvaluateActions(HashDigest`1 preEvaluationHash, Int64 blockIndex, Int32 blockProtocolVersion, Nullable`1 txid, IWorld previousStates, Address miner, Address signer, Byte[] signature, IImmutableList`1 actions, ILogger logger)+MoveNext() in /home/ulismoon/Documents/planetarium/NineChronicles.Headless/NineChronicles.Headless.Executable/Commands/ReplayCommand.Privates.cs:line 129
```
ice sield / frostbite 관련 내용이 없는 것 같습니다.

**Comment by U-lis** [comment]
이 이슈는 AdventureBossSimulator 에 BuffLinkSheet 를 전달하지 않아서 생기는 이슈로 확인되었습니다.
Lib9c 수정이 필요한 부분으로, 패치 진행하도록 하겠습니다.
